// <auto-generated />
using System;
using HousingMap.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HousingMap.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HousingMapDbContext))]
    [Migration("20260924100240_InitialGisSchema")]
    partial class InitialGisSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HousingMap.Domain.Datasets.GisDataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Crs")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("crs");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDevelopmentData")
                        .HasColumnType("boolean")
                        .HasColumnName("is_development_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_gis_datasets");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_gis_datasets_is_active")
                        .HasFilter("is_active");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ix_gis_datasets_version");

                    b.ToTable("gis_datasets", (string)null);
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<MultiPolygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_blocks_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_blocks_sector_id");

                    b.HasIndex("DatasetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_dataset_id_code");

                    b.HasIndex("DatasetId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_dataset_id_source_id");

                    b.ToTable("blocks", (string)null);
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Plot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AreaSquareMetres")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("area_square_metres");

                    b.Property<string>("AuthorityReference")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("authority_reference");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<Point>("CenterPoint")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("center_point");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("dimensions");

                    b.Property<MultiPolygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("PlotNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plot_number");

                    b.Property<string>("PlotType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plot_type");

                    b.Property<Guid?>("RoadId")
                        .HasColumnType("uuid")
                        .HasColumnName("road_id");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StreetId")
                        .HasColumnType("uuid")
                        .HasColumnName("street_id");

                    b.HasKey("Id")
                        .HasName("pk_plots");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("ix_plots_block_id");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_plots_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("RoadId")
                        .HasDatabaseName("ix_plots_road_id");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_plots_sector_id");

                    b.HasIndex("StreetId")
                        .HasDatabaseName("ix_plots_street_id");

                    b.HasIndex("DatasetId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_plots_dataset_id_source_id");

                    b.HasIndex("DatasetId", "SectorId", "PlotNumber")
                        .HasDatabaseName("ix_plots_dataset_id_sector_id_plot_number");

                    b.ToTable("plots", (string)null);
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.PointOfInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_points_of_interest");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_points_of_interest_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("DatasetId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_points_of_interest_dataset_id_source_id");

                    b.ToTable("points_of_interest", (string)null);
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Road", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<MultiLineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiLineString,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("RoadType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("road_type");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_roads");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_roads_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("DatasetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_roads_dataset_id_code");

                    b.HasIndex("DatasetId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_roads_dataset_id_source_id");

                    b.ToTable("roads", (string)null);
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<MultiPolygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_sectors");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_sectors_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("DatasetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sectors_dataset_id_code");

                    b.HasIndex("DatasetId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_sectors_dataset_id_source_id");

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Street", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<MultiLineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiLineString,4326)")
                        .HasColumnName("geometry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_id");

                    b.HasKey("Id")
                        .HasName("pk_streets");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("ix_streets_block_id");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_streets_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("DatasetId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_streets_dataset_id_code");

                    b.HasIndex("DatasetId", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_streets_dataset_id_source_id");

                    b.ToTable("streets", (string)null);
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Block", b =>
                {
                    b.HasOne("HousingMap.Domain.Datasets.GisDataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_gis_datasets_dataset_id");

                    b.HasOne("HousingMap.Domain.Gis.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_sectors_sector_id");

                    b.Navigation("Dataset");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Plot", b =>
                {
                    b.HasOne("HousingMap.Domain.Gis.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plots_blocks_block_id");

                    b.HasOne("HousingMap.Domain.Datasets.GisDataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plots_gis_datasets_dataset_id");

                    b.HasOne("HousingMap.Domain.Gis.Road", "Road")
                        .WithMany()
                        .HasForeignKey("RoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plots_roads_road_id");

                    b.HasOne("HousingMap.Domain.Gis.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plots_sectors_sector_id");

                    b.HasOne("HousingMap.Domain.Gis.Street", "Street")
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_plots_streets_street_id");

                    b.Navigation("Block");

                    b.Navigation("Dataset");

                    b.Navigation("Road");

                    b.Navigation("Sector");

                    b.Navigation("Street");
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.PointOfInterest", b =>
                {
                    b.HasOne("HousingMap.Domain.Datasets.GisDataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_points_of_interest_gis_datasets_dataset_id");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Road", b =>
                {
                    b.HasOne("HousingMap.Domain.Datasets.GisDataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roads_gis_datasets_dataset_id");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Sector", b =>
                {
                    b.HasOne("HousingMap.Domain.Datasets.GisDataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sectors_gis_datasets_dataset_id");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("HousingMap.Domain.Gis.Street", b =>
                {
                    b.HasOne("HousingMap.Domain.Gis.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_streets_blocks_block_id");

                    b.HasOne("HousingMap.Domain.Datasets.GisDataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_streets_gis_datasets_dataset_id");

                    b.Navigation("Block");

                    b.Navigation("Dataset");
                });
#pragma warning restore 612, 618
        }
    }
}
